- name: Delete previous template file
  file: >
    path={{ nginx_path }}/sites-available/15-default.conf
    state=absent

- name: Force logrotate configuration (Fix postrotate command in Ubuntu 16)
  template: src=logrotate.nginx.conf dest=/etc/logrotate.d/nginx
  tags: nginx-logrotate

- name: Template nginx conf
  template: src=nginx.conf.j2 dest={{ nginx_path }}/nginx.conf
  notify: restart nginx
  tags: default_nginx_conf
