---
- name: Install sudo
  apt: name=sudo state=present
  when: ansible_distribution == 'Debian'

- name: Install basic packages
  include: basic_packages.yml
  tags: basic_packages

- name: Configure Uncomplicated Firewall (UFW)
  include: ufw.yml
  tags: ufw
