---
- hosts: all
  remote_user: root
  become: true

  vars:
    - app_name: sirene_production
    - db_name: sirene_as_api
    - db_adapter: postgresql
    - rails_env: production
    - environment_config_log_level: :debug
    - client_server_name: #MY_SERVER.com
    - client_secret_key_base: #MY_SECRET_KEY_BASE
    - client_secret_db_password: #MY_SECRET_DB_PASSWORD

  roles:
    - { role: python_install_raw, tags: ['python_raw'] }
    - { role: deploy_user, tags: ['deploy_user'] }
    - { role: nginx, mina_deploy: true, tags: ['nginx'] }
    - { role: rails_app, tags: sirene_rails_app }
    - { role: ruby, tags: ['ruby', 'rbenv'] }
    - { role: sirene, tags: sirene }
    - { role: postgresql, tags: postgresql }
