---
- name: Install tmux
  apt:
    name: tmux
    state: latest

- name: Set .tmux directory owner for {{ username }}
  become: true
  file:
    path:     '~/.tmux'
    group:    '{{ username }}'
    owner:    '{{ username }}'
    state:    directory
    mode:     '0755'
    recurse:  true

- name: Clone tmux Plugin Manager for {{ username }}
  become_user: '{{ username }}'
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '~/.tmux/plugins/tpm'
    update: no

- name: Copy tmux.conf file for {{ username }}
  become_user: '{{ username }}'
  copy:
    src:    './files/tmux/tmux.conf'
    dest:   '~/.tmux.conf'
    mode:   '0644'

- name: Check if some tmux are running
  become_user: '{{ username }}'
  shell: 'tmux ls | wc -l'
  register: tmux_ls

- name: Source .tmux for tpm
  become_user: '{{ username }}'
  command: 'tmux source ~/.tmux.conf'
  when: tmux_ls.stderr == ""

- name: Install tmux plugins for {{ username }}
  become_user: '{{ username }}'
  command: '~/.tmux/plugins/tpm/bin/install_plugins'
